### ISSUE TITLE
Security audit queries

### ISSUE THREAD

**Issue by rndagijimana** [Mibew/mibew#115]
I have run a vulnerability scan and these notifications show up

```
----------------------------------------------------
User credentials are sent in clear text
-----------------------------------------------------
..../operator/login.php
..../operator/restore.php
------------------------------------------------------
HTML form without CSRF protection
------------------------------------------------------
..../operator/login.php
..../operator/restore.php
```

how can we avoid these vulnerabilities???

**Comment by JustBlackBird** [comment]
First of all, you should use either github issues or form to post the message but definitely not both. As you can see it does not make us answer you faster.

The first part of the report (about credentials) can be fixed by using `https` on you server. It's not a Mibew vulnerability.

As for the second part of the report (CSRF protection), it can be treated as a problem but it does not seems to be critical. The good news are we'll likely fix it in Mibew 2.0.0-beta.4. The bad news are I don't think we'll fix it in 1.6.x branch soon. So if you use 1.6.x branch you can either update it to 2.0.x branch or create a pull request with the fix.

Also I've updated the original message for make it more readable.

**Comment by JustBlackBird** [comment]
CSRF protection is added in Mibew 2.0 with 3c0c880661b445342d272fb21ea261ae7ef36931 and e122d020eb35db0397bacdbc02015fa7f73fc56d, so I close the issue. If you want CSRF protection in 1.6.x branch -- create a pull request for that.

**Comment by rndagijimana** [comment]
Thanks Dmitriy,  am so greatful

**Comment by rndagijimana** [comment]
@JustBlackBird ; thank you, am so grateful!
