### ISSUE TITLE
How to show the date of message?

### ISSUE THREAD

**Issue by hp3240au** [Mibew/mibew#122]
how to show the message date and time in history page?
here is the link of preview page
http://tuku.youni.net.cn/showphoto.php?k=var/resizes/youbao/yulanyoubao3.png&m=1429511222

**Comment by JustBlackBird** [comment]
Actually there is no simple way of doing so. Also I assume you are talking about Mibew 2.0 because Mibew 1.6.x branch is deprecated now.

The solution is related with altering pages style. You can create new style based on existing one on patch the default style. To make the solution work you should have basic developer skills. Here are the instructions of patching the existing style:

1. Get Mibew repository.

2. Add Handlebars.js helper that will format day. Put the following lines into `styles/pages/default/js/helpers.js`:
    ```javascript
    (function (Handlebars){
        Handlebars.registerHelper('formatDate', function(unixTimestamp){
            var d = new Date(unixTimestamp * 1000);
            return d.toString(); // You can use any format you want here.
        });
    })(Handlebars);
    ```
3. Alter `styles/pages/default/templates_src/server_side/_layout.handlebars` and add the following line after `{{jsAssets}}`:
    ```html
    <script type="text/javascript" src="{{asset "@CurrentStyle/js/helpers.js"}}"></script>
    ```

4. Alter [this template](https://github.com/Mibew/mibew/blob/master/src/mibew/styles/pages/default/templates_src/client_side/message.handlebars#L1) and replace `formatTime` with `formatDate`.

5. Rebuild the sources. Read [this](https://github.com/Mibew/mibew/blob/master/README.md#build-from-sources) about how it could be done.

One more thing. This is a question not an issue. It's better to post such questions at our forum: https://mibew.org/forums/

**Comment by hp3240au** [comment]
I will try it.Thank you!(register is bad of the forums)

**Comment by JustBlackBird** [comment]
Cool. For now I'm closing the issue.

**Comment by hp3240au** [comment]
errored coding.need your help?

**Comment by hp3240au** [comment]
![gulp-coding](https://cloud.githubusercontent.com/assets/6030325/7270010/6201cc68-e90b-11e4-924f-9c8044c845b1.png)

**Comment by JustBlackBird** [comment]
The first. It's a separated problem related with the build process, so new thread should be created for it. Just remember that it's not a private conversation and we try to make the issues searchable for other users.

The second **it's not an issue** use the forum for such questions.

**Comment by hp3240au** [comment]
ok.I will go to forum.Thank you.
