### ISSUE TITLE
Group isolation

### ISSUE THREAD

**Issue by ceylani** [Mibew/mibew#131]
"enable groups isolation" setting is not great working the operator console wide. 

For example you checked the above option.
On statistics page, statistics are calculating and showing for all of operators (by date or by operator).
When you want to add a canned message in operator panel, the message is adding global canned messages and the group information does not shown in the group combobox.

**Comment by JustBlackBird** [comment]
What version of Mibew are you talking about?

**Comment by ceylani** [comment]
2.1.0

**Comment by JustBlackBird** [comment]
You've mentioned several different problems in this issue. Everything but statistics is fixed with 4c9f963aa73ec4844fc55eef51e1b7f472e2ca55. As for statistics, all its calculation algorithms should be reviewed and (may be) rewritten. So I don't think it'll be fixed in the upcoming release.

**Comment by ceylani** [comment]
I have made a test and it's okay. 
Thanks

**Comment by myabo** [comment]
Warning: Application stopped because of uncaught exception Stash\Exception\WindowsPathMaxLengthException "Cache path exceeds Windows PHP MAX_LENGTH of 260 characters. " (C:\usr\www\test.ru\operator\vendor\tedivm\stash\src\Stash\Driver\FileSystem.php:229) in C:\usr\www\test.ru\operator\libs\classes\Mibew\Application.php on line 165
Internal Server Error

**Comment by JustBlackBird** [comment]
The part of the issue about statistics was moved to separated issue. See #139

**Comment by JustBlackBird** [comment]
@myabo You should create a new issue because you problem has nothing with the current issue.
