### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by marcelonhenhe** [Mibew/mibew#156]
Hi, when I try to install the new version of the program, the install.php redirects to "/install.php/install/check-requirements" and this page don't exist on my server... how do I install it?

**Comment by JustBlackBird** [comment]
`/install.php/install/check-requirements` is not a real file. It's just a route that is processed by Mibew.

To help you install Mibew you should help us first:
1. What web server do you use?
2. What OS do you use?
3. What version of PHP do you use?
4. What exactly do you do and what error do you get?
5. Are there any messages in error log?

**Comment by programadorluis** [comment]
HOLA PORFAVOR ME AYUDAN A INSTALAR MIBEW 2.1.1
EL SERVER ES: LOCALHOST DE (XAMPP)
SISTEMA OPERATIVO: (WINDOWS 7)
PHP Version 5.6.15
Y MI GRAN PREGUNTA ES:?????

COMO HAGO LA INSTALACION.... YA QUE DESCARGO EL PAQUETE DE LA PAGINA DE MIBEW Y ES DIFERENTE A ESTA Q USTEDES DAN AQUI.

EN  LA OTRA ME DA ERROR PORQUE ME PIDE Q DE PERMISOS 0700 CHMOD Y NO TENGO IDEA DE QUE O COMO SE HACE ESO..

ME DAS UN OPASO A PASO POR FAVOR URGENTE DE LA ISTALACION

**Comment by faf** [comment]
@programadorluis, 

1. Please, use English when you asking a question. We don't speak Spanish and even if we do in this case it would be a little bit disrespectfully to the community.

2. Do you have exactly the same issue as the topic starter? If you don't, please fill another issue.

NB: Your original comment and this answer will be removed in three days.

**Comment by faf** [comment]
Closed due to inactivity.

**Comment by programadorluis** [comment]
HELLO PLEASE HELP ME TO INSTALL 2.1.1 Mibew
THE SERVER IS : localhost ( XAMPP )
OPERATING SYSTEM: ( WINDOWS 7)
PHP Version 5.6.15
AND MY BIG QUESTION IS : ?????

HOW I DO THE INSTALLATION .... AS PACK RELEASE PAGE Mibew AND DIFFERENT YOU GIVE THIS Q HERE .

IN THE OTHER ME BECAUSE I ASK DA ERROR Q CHMOD 0700 PERMITS AND I HAVE NO IDEA HOW YOU OR THAT GETS ..

GIVE ME ONE STEP SEAFO URGENT PLEASE THE Install,

**Comment by programadorluis** [comment]
in some cases none I have to put in the config file to start it because the filesysten not work in the cahe

**Comment by faf** [comment]
@programadorluis,

One more time (and for the last time) Do you have **exactly the same issue as the topic starter**? If you don't, please fill **another** issue.

And please use the most simple sentences when using translation tool. For now I just don't understand what's your problem.

**Comment by programadorluis** [comment]
------My problem is this WHEN finished installing Mibew 2.1

Warning: Application stopped because of uncaught exception Stash\Exception\WindowsPathMaxLengthException "Cache path exceeds Windows PHP MAX_LENGTH of 260 characters. " (C:\xampp\htdocs\mibew\vendor\tedivm\stash\src\Stash\Driver\FileSystem.php:229) in C:\xampp\htdocs\mibew\libs\classes\Mibew\Application.php on line 165
Internal Server Error

-----and then asks me to give permission to the folders with chmod 0777

----
I also want to know where are the lines to change the folder directory Mibew



beforehand please thanks

**Comment by programadorluis** [comment]
that mistake I show you up if I put in me none if the application runs well

**Comment by faf** [comment]
@programadorluis Oh, come on...

https://mibew.org/forums/index.php/topic,191999.msg199151.html
https://mibew.org/forums/index.php/topic,191933.msg198907.html
https://mibew.org/forums/index.php/topic,191803.msg198382.html
