### ISSUE TITLE
Block chat history

### ISSUE THREAD

**Issue by heihachi88** [Mibew/mibew#16]
Currently every user can view the chat history of all operators independent of the group he belongs to. 

We need to have such options:
Every operator can watch only his chat history;
Every operator can watch only his group chat history;

history.php should be fixed.

**Comment by JustBlackBird** [comment]
Frankly, I forgot about the issue. Nevertheless, Mibew is now stable enough so I believe somebody could create a pull request for this :wink:

**Comment by JustBlackBird** [comment]
It's somehow fixed in 5009f513423ac6c409fc84c1f5dc926e9e3927b0, aa0c213cc3936a30363f31a6981d041ee87dab0a and 896f090abad6f8c3c8db7675c586e9018c9d1468. The fix will be released in `2.1.0`.

There are no new permissions added. The access to history is based on the current Mibew permissions model. Here is a tiny description of how it works:

1. Operators with "can administrate" permission can view all history.
2. Operators without "can view threads" permission can view only their own history.
3. If the groups isolation is on, operators with "can view threads" permission can view history only for adjacent groups.
4. If the groups isolation is off, operators with "can view threads" permission can view all history.
