### ISSUE TITLE
PHP MAX_LENGTH of 260 characters on Windows

### ISSUE THREAD

**Issue by candido1212** [Mibew/mibew#165]
This issue is only for knowledge

OS: Windows 7
XAMPP PHP 5.6.23

mibew\configs\config.yml
    storage: file_system

Warning: Application stopped because of uncaught exception Stash\Exception\WindowsPathMaxLengthException "Cache path exceeds Windows PHP MAX_LENGTH of 260 characters. " (C:\Projetos\php\mibew2x\src\mibew\vendor\tedivm\stash\src\Stash\Driver\FileSystem.php:229) in C:\Projetos\php\mibew2x\src\mibew\libs\classes\Mibew\Application.php on line 165
Internal Server Error

**Comment by JustBlackBird** [comment]
Windows platforms can have problems with too long cache files path. That's why this check exists.

You have several options:
1. Do not use windows platforms
2. Use another cache storage (see https://github.com/Mibew/mibew/blob/master/src/mibew/configs/default_config.yml#L42)
3. Try to place several levels upper in file tree.

**Comment by webdevlabs** [comment]
I experienced the same issue while development on the windows platform. I don't have any experience with Mibew, just got here while searching for a solution. 
Here is my easy solution for this problem in Stash:
`$item = $this->cache->getItem('/group'.md5('/key/here'));`
Notice that you must use shorter group names. 
If you still get the error you can put the whole key as md5 string, but you will loose the **grouping** features.
Hope this helps someone. I really enjoy using stash in my project.
