### ISSUE TITLE
Bug: Inconsistent URL Path

### ISSUE THREAD

**Issue by MichaelTunnell** [Mibew/mibew#180]
The URL path for stuff in Mibew is inconsistent at times based on the page you are currently on.

For example: 
When you want to edit Operator 1 while on the dashboard the URL would be:
http://example.com/mibew/operator/1/edit

However, the actual URL should be:
http://example.com/mibew/operator/operator/1/edit

I'd suggest a variable like $baseurl or something that contains a configurable yet permanent path that can be used anywhere.

**Comment by JustBlackBird** [comment]
Cannot confirm.

Let's take our [demo installation](https://demo2.mibew.org/) as an example. There is only two links to operator's profile from the dashboard:

1. In the right top corner (the link in "_You are Administrator_" message).
2. At "Profile" tile.

Both links are `https://example.com/operator/operator/1/edit`.

**Comment by MichaelTunnell** [comment]
I'm not referring to just the dashboard. I found this issue by restructuring the design with my new theme. Setup the theme, I sent to you in email, on test install of Mibew and you will see this issue happen guaranteed.

**Comment by JustBlackBird** [comment]
Then may be something is wrong with your theme?

You see Mibew uses one URL generator for all the URL used in template (I really believe in it :smile:). This is how we output "_You are Administrator_" message:

```handlebars
{{{l10n "You are <a href=\"{0}\">{1}</a>" (route "operator_edit" operator_id=currentopid) operator}}}
```
As you can see there is no base path manually specified here. And it's actually is not needed here because all the mess with URLs generation is implemented in [Handlebars Route Helper](https://github.com/Mibew/mibew/blob/master/src/mibew/libs/classes/Mibew/Handlebars/Helper/RouteHelper.php).

**Comment by MichaelTunnell** [comment]
After further testing, my bad. I was implementing the routing wrong which caused the issue. I've fixed it on my end. :) Still learning handlebars it seems.
