### ISSUE TITLE
Mixed Content with HTTPS Connection

### ISSUE THREAD

**Issue by gnomee2** [Mibew/mibew#206]
When loading button code on a HTTPS site, chat_popup.js loads iframe.css via HTTP even though the connection his HTTPS.

Therefore the browser blocks the content and mibew will not function properly on the site.

Temporary workaround is to include the style manually in your site template

https://YOUR MIBEW DOMAIN/styles/chats/YOUR STYLE/iframe.css

**Comment by faf** [comment]
You should be more specific about your installation of Mibew Messenger. Provide more details about your environment and the options you used to generate the button.

**Comment by gnomee2** [comment]
That make sense, sorry about that.

Mibew version 2.2.3

Localization: en

Custom Style which is just default style and then the logo image changed to a different image.

Custom button located in Localization. 

Environment:
PHP 5.6.30-0+deb8u1 PDO/1.0.4dev pdo_mysql/1.0.2 gd curl mbstring 

Using Turnkey.org Mibew install.

Button settings used custom images in local, custom style in chat window and invitation style. Host name included and use secure links checked.

Mibew his hosted at https:///chat.mydomain.com

Website is https://mysite.com

**Comment by faf** [comment]
> Using Turnkey.org Mibew install.

To begin with we know nothing about the service (?) you use to install Mibew Messenger. So we definitely are unable to reproduce the troubled environment.

At the same time one have to admit that generation of the button could be a little bit tricky when the application works behind a proxy. For example take a look at [this issue](https://github.com/Mibew/mibew/issues/192) that was solved by [this PR](https://github.com/Mibew/mibew/pull/194).

Maybe you should adjust the configuration and add there a `trusted_proxies` option.

**Comment by gnomee2** [comment]
No service or PROXY. Typo.. https://www.turnkeylinux.org/mibew

Just a pre-configured ISO for the server and only thing running on it.

**Comment by gnomee2** [comment]
You can see it in action at www.accreditationnow.com

**Comment by faf** [comment]
As it can be seen from HTTP headers your Mibew Messenger works behind nginx. It's proxy. So the problem is in the invalid configuration for this particular distro prepared by some third party project. Moreover I've already pointed you at the most likely solution.

Also you could try to get support from turnkeylinux.org. It looks like their issue, not ours.

**Comment by claflico** [comment]
@faf I'm the DevOps engineer maintaining the infrastructure that the accnow site is running on. 

We use an Nginx reverse-proxy load-balancer to handle ssl termination on the front end and connect to non-https upstreams. The mibew install running on Turnkey does appear to have a couple customizations at install however upon review of the source in this repo it looks to be the same as the current release except that it was missing the trusted_proxies array variable in the config. 

Everything on the chat url appears to work behind the load-balancer as far as I can tell EXCEPT for the iframe.css file. I enabled the SSL configs in the settings page but that seemed to have no effect on anything. After reading  #194 I added the trusted_proxies variable with the IP of our load-balancer to config.yaml and restarted apache but didn't resolve the issue. 

After some trial and error, what I found I had to do was add the SSL cert to the server hosting the mibew application and then configure the nginx load-balancer to use HTTPS to connect to the upstream server rather than HTTP. After that I no longer get the browser warning on the iframe.css file. 

This works for now but it is causing us to do double ssl termination. I don't see any Docker containers for Mibew other than some from Turnkey (these ARE NOT what we are using) so I might try and see if I can get the application installed from scratch on a Dev server to confirm if the issue still exists.

**Comment by faf** [comment]
@claflico 

> We use an Nginx reverse-proxy load-balancer to handle ssl termination on the front end and connect to non-https upstreams

Yes, that's a typical use case for nginx. Our [demo](https://demo2.mibew.org) works the same way.
But for the backend (Apache) we just use [env_module](http://httpd.apache.org/docs/current/mod/mod_env.html) with a given configuration:

```
        <IfModule env_module>
            SetEnv HTTP_PORT 443
            SetEnv HTTP_SCHEME https
            SetEnv HTTPS on
            SetEnv HTTP_HOSTNAME demo2.mibew.org
        </IfModule>
```

That's why I've said that the process could be a little bit tricky.

> Everything on the chat url appears to work behind the load-balancer as far as I can tell EXCEPT for the iframe.css file.

That's very strange.

> This works for now but it is causing us to do double ssl termination.

So, actually it's not a solution for production environment..

> I might try and see if I can get the application installed from scratch on a Dev server to confirm if the issue still exists.

Yes, that would be great.

One need to reproduce the issue. And then one need to figure out why does the issue exists, and how it can be solved.

**Comment by faf** [comment]
@claflico Were you able to check the issue?

**Comment by faf** [comment]
@gnomee2 Are the issue is still relevant?
