### ISSUE TITLE
Error installing Mibew

### ISSUE THREAD

**Issue by tushroy** [Mibew/mibew#232]
URL: http://localhost/mibew/install.php/install/create-tables

Correct the mistakes:
Cannot create tables. Error: Query failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function varchar(64) NOT NULL, arguments varchar(1024), INDEX token (token)) cha' at line 1

Completed:

    PHP version 5.6.32
    All necessary PHP extensions are loaded
    Directories permissions are correct
    You are connected to MySQL server version 8.0.12

**Comment by faf** [comment]
1. I suppose that the issue is related to the new reseved word `function` that [was introduced](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-F) in Oracle's MySQL 8. Take a look at the new branch `mysql_fix`. The solution is there, but you'll have to check it.

2. One should use an issues template when reporting a bug. Please respect the devs.

**Comment by faf** [comment]
@tushroy Have you checked the solution?

**Comment by tushroy** [comment]
@faf Yes, Fix is working properly.
