### ISSUE TITLE
Invitation in "text link" button

### ISSUE THREAD

**Issue by bocceli** [Mibew/mibew#239]
### Environment
* Mibew Messenger version: 3.2.1
* OS: Windows 10
* Web server: Apache
* PHP: 7.0
* PHP extensions: all required
* MySQL: not substantial
### Expected behavior
Generated code for text button contain code for invitation and invitation style. Button generation gui sould render select field to select invitation style.
### Actual behavior
Generated button of type "text link" does not contain invitation code. And gui for button generation does not render invitation style select.
### Steps to reproduce the behavior
Just select "text link" in button generation

**Comment by faf** [comment]
Actually, that feature works as intended.

Text links were supposed to be used in emails, instant  essages, etc. to provide an ability to chat with an operator. It was not supposed to be used on sites, so there was no need to implement tracking and inviting for that type of chat buttons.

Moreover, tracking and inviting doesn't implemented for 'operator code' button type too. Since one should know a code of an operator to make use of such button. Interactive behaviour in this case is unexpected and unwanted.

**Comment by faf** [comment]
You're welcome.

And if you'll share your modifications, maybe I'll be able to incorporate them into the master branch. ;) Maybe in some circumstances it could be useful for users to be able to use invites alongside with text links.

**Comment by bocceli** [comment]
I will try solve this problem in few days. If I come with elegant solution I'll share it with pleasure ;)
