### ISSUE TITLE
Is that possible to get MS SQL server Implementation?

### ISSUE THREAD

**Issue by emmanuelcolina** [Mibew/mibew#244]
Hi, Is that possible to get MS SQL server Implementation?

**Comment by faf** [comment]
Well, in theory, since the database layer is based upon PDO, it is possible. But, to begin with why should anyone need that?

**Comment by emmanuelcolina** [comment]
I need to do a proyect based mibew y Sql server 2017, any suggest? i need help please.

**Comment by emmanuelcolina** [comment]
![image](https://user-images.githubusercontent.com/11465368/56211471-fc08c380-6025-11e9-9a16-406b982c54cb.png)

Check that, i got tha connect to sql server, but have a error here

![image](https://user-images.githubusercontent.com/11465368/56211572-28bcdb00-6026-11e9-8af6-f792be701c7c.png)

i guess what that sintaxys (CREATE TABLE IF NOT EXISTS) not work in sql server

**Comment by faf** [comment]
Well. Just read the fine manual for M$ SQL Server and alter the database related code so that it became compatible with that proprietary database software.

You see, you've wrote why **you** need that. But it's useless for **anyone else**. It's neither interesting, nor useful for Mibew project, so you're on your own here.

**Comment by emmanuelcolina** [comment]
Ok Thk! :)
