### ISSUE TITLE
Name missing from the chat window if using a custom url and users aren't allowed to edit their name

### ISSUE THREAD

**Issue by effgarces** [Mibew/mibew#265]
### Environment
* Mibew Messenger version: 3.5.1
* OS: RHEL 7.9
* Web server: Apache
* PHP: 7.4
* PHP extensions:
* MySQL: 8
### Expected behavior
Using a custom link to the chat, that includes the user name and email, and with the option to allow for the users to edit their name disabled, the name of the user should display in the pre-chat form and then afterwards the same name should show up on the chat as their name
### Actual behavior
If the option that allows the users to edit their name in the chat window is disabled, then using the previously mentioned custom url to the chat their name shows up on the pre-chat form but when entering the chat window the name is nowhere to be found, also when chatting they are identifiied by "Visitor" instead of the name that was pre-filed on the pre-chat form.
### Steps to reproduce the behavior
Disable the option that allows users to edit their name
Enable the pre-chat form
Enter a chat through a custom link like:
https://yourserver/mibew/chat?locale=pt-pt&group=1&name=ExampleName&email=example@email.com

**Comment by faf** [comment]
> Expected behavior
Using a custom link to the chat, that includes the user name and email, and with the option to allow for the users to edit their name disabled, the name of the user should display in the pre-chat form and then afterwards the same name should show up on the chat as their name

No, that's not an expected behaviour. You're trying to misuse an undocumented feature.

If you restrict a user to change his name, it means that the name should not be altered using the standard interface. It's very simple for an user to alter a value of a disabled field, and it's impossible for an application to separate your custom value of the name field from a value that was altered by an user. That's why the name field in pre-chat survey form is disabled and its value is ignored after the form submission. And that's a normal behaviour.

If you really need to somehow dynamically set a user's name while restricting to change it, you'll have to write a plugin for that.
